Repository moodbook-space/moodbook-backend, pull requests merged in 2025-07, with the labels that each got.

#3 Feature/login - 로그인 관련 PR 요청
  build.gradle
  src/main/java/org/com/moodbook/MoodbookApplication.java
  src/main/java/org/com/moodbook/common/constants/Gender.java
  src/main/java/org/com/moodbook/common/constants/Role.java
  src/main/java/org/com/moodbook/common/constants/UserStatus.java
  src/main/java/org/com/moodbook/user/entity/BaseTime.java
  src/main/java/org/com/moodbook/user/entity/User.java
  src/main/java/org/com/moodbook/user/entity/UserProfile.java
Labels: ✨ Feature

#7 application.yml 변경
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ⚙️ Setting

#12 Feature/mypage - Book Entity, BookDTO 생성
  src/main/java/org/com/moodbook/book/dto/BookDTO.java
  src/main/java/org/com/moodbook/book/entity/Book.java
  src/main/java/org/com/moodbook/common/constants/Language.java
Labels: ✨ Feature

#17 application.yml 분기 처리
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/applidation-dev.yml
Labels: ⚙️ Setting

#21 Feature/#18
  build.gradle
  src/main/resources/application-local.yml
Labels: ⚙️ Setting

#22 chore/#20 - Book Entity, Repository, DTO ERDCloud와 알맞게 수정
  src/main/java/org/com/moodbook/book/dto/BookDTO.java
  src/main/java/org/com/moodbook/book/entity/Book.java
  src/main/java/org/com/moodbook/book/repository/BookRepository.java
Labels: 🚮 chore

#24 Feature/#23 EmotionScore 분석 entity, service, controller, repository 생성
  src/main/java/org/com/moodbook/book/repository/BookRepository.java
  src/main/java/org/com/moodbook/common/constants/Role.java
  src/main/java/org/com/moodbook/common/constants/UserStatus.java
  src/main/java/org/com/moodbook/emotion/controller/BookEmotionController.java
  src/main/java/org/com/moodbook/emotion/controller/EmotionController.java
  src/main/java/org/com/moodbook/emotion/dto/BookEmotionScoreRequest.java
  src/main/java/org/com/moodbook/emotion/dto/BookEmotionScoreResponse.java
  src/main/java/org/com/moodbook/emotion/entity/BookEmotionScore.java
  src/main/java/org/com/moodbook/emotion/repository/BookEmotionScoreRepository.java
  src/main/java/org/com/moodbook/emotion/service/BookEmotionService.java
  src/main/java/org/com/moodbook/emotion/service/EmotionAnalyzer.java
Labels: ✨ Feature

#25 Feature/#19-JWT token 관련 filter일부/provider/key및 security 적용
  build.gradle
  src/main/java/org/com/moodbook/book/entity/Book.java
  src/main/java/org/com/moodbook/common/model/BaseTime.java
  src/main/java/org/com/moodbook/member/controller/MemberController.java
  src/main/java/org/com/moodbook/member/dto/MemberDTO.java
  src/main/java/org/com/moodbook/member/dto/MemberProfileDTO.java
  src/main/java/org/com/moodbook/member/entity/Member.java
  src/main/java/org/com/moodbook/member/entity/MemberProfile.java
  src/main/java/org/com/moodbook/member/repository/MemberProfileRepository.java
  src/main/java/org/com/moodbook/member/repository/MemberRepository.java
  src/main/java/org/com/moodbook/security/config/SecurityConfig.java
  src/main/java/org/com/moodbook/security/core/CustomMemberDetails.java
  src/main/java/org/com/moodbook/security/jwt/JwtKey.java
  src/main/java/org/com/moodbook/security/jwt/JwtTokenFilter.java
  src/main/java/org/com/moodbook/security/jwt/JwtTokenProvider.java
  src/main/java/org/com/moodbook/threadlocal/TraceIdHolder.java
Labels: ✨ Feature

#33 [Chore] 기타 업무 - exception(ErrorCode) #32
  src/main/java/org/com/moodbook/common/exception/ErrorCode.java
Labels: 🚮 chore

#38 Test/#13 - Rebase 검증을 위한 PR
  build.gradle
  src/main/java/org/com/moodbook/common/config/S3Config.java
  src/main/java/org/com/moodbook/common/util/FileNameGenerator.java
  src/main/java/org/com/moodbook/common/util/UuidFileNameGenerator.java
  src/main/java/org/com/moodbook/s3/controller/S3Controller.java
  src/main/java/org/com/moodbook/s3/service/S3Service.java
  src/main/java/org/com/moodbook/s3/service/S3ServiceImpl.java
  src/main/resources/application-local.yml
Labels: 🚮 chore

#45 Feat/#44 무드태그 기능코드 구현
  src/main/java/org/com/moodbook/post/entity/MoodTag.java
  src/main/java/org/com/moodbook/post/repository/MoodTagRepository.java
Labels: ✨ Feature

#53 [Chore] 기타 업무 - application.yml 파일 수정(ddl-auto 추가) + ErrorCode 수정
  src/main/java/org/com/moodbook/common/exception/ErrorCode.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/applidation-dev.yml
Labels: 🚮 chore

#56 fix(entity)- BookEmotionScoreResponse 타입 미스매치 수정
  src/main/java/org/com/moodbook/emotion/dto/BookEmotionScoreResponse.java
Labels: 🐞 Bugfix

#60 Feat/#58 독서모임 관련 추가 기능 구현(수정, 삭제, 모임 신청, 승인/거절, 신청 목록 조회)
  src/main/java/org/com/moodbook/common/exception/ErrorCode.java
  src/main/java/org/com/moodbook/post/controller/MeetingController.java
  src/main/java/org/com/moodbook/post/dto/MeetingJoinDto.java
  src/main/java/org/com/moodbook/post/dto/MeetingJoinRequest.java
  src/main/java/org/com/moodbook/post/dto/MeetingJoinResponseRequest.java
  src/main/java/org/com/moodbook/post/dto/UpdateMeetingRequest.java
  src/main/java/org/com/moodbook/post/service/MeetingService.java
  src/main/java/org/com/moodbook/post/service/impl/MeetingServiceImpl.java
Labels: ✨ Feature, 🚮 chore

#62 Feat/#39 - AWS S3 파일 업로드 구현
  src/main/java/org/com/moodbook/awss3/controller/AWSS3Controller.java
  src/main/java/org/com/moodbook/awss3/service/AWSS3Service.java
  src/main/java/org/com/moodbook/awss3/service/AWSS3ServiceImpl.java
  src/main/java/org/com/moodbook/common/config/AWSS3Config.java
  src/main/java/org/com/moodbook/common/config/S3Config.java
  src/main/java/org/com/moodbook/common/exception/BaseException.java
  src/main/java/org/com/moodbook/common/exception/ErrorCode.java
  src/main/java/org/com/moodbook/common/util/AWSS3Uploader.java
  src/main/java/org/com/moodbook/common/util/AWSS3UploaderImpl.java
  src/main/java/org/com/moodbook/common/util/FileNameGenerator.java
  src/main/java/org/com/moodbook/common/util/FileNameGeneratorImpl.java
  src/main/java/org/com/moodbook/member/entity/MemberProfile.java
  src/main/java/org/com/moodbook/s3/service/S3ServiceImpl.java
Labels: ✨ Feature

#63 Feature/#57
  src/main/java/org/com/moodbook/common/exception/BaseException.java
  src/main/java/org/com/moodbook/common/exception/ErrorCode.java
  src/main/java/org/com/moodbook/member/controller/MemberController.java
  src/main/java/org/com/moodbook/member/dto/MemberLoginDTO.java
  src/main/java/org/com/moodbook/member/repository/MemberRepository.java
  src/main/java/org/com/moodbook/member/service/MemberService.java
  src/main/java/org/com/moodbook/member/service/MemberServiceImpl.java
  src/main/java/org/com/moodbook/post/service/impl/MeetingServiceImpl.java
  src/main/java/org/com/moodbook/post/service/impl/ReportServiceImpl.java
  src/main/java/org/com/moodbook/security/authentication/repository/AuthenticationReposiroty.java
  src/main/java/org/com/moodbook/security/config/SecurityConfig.java
  src/main/java/org/com/moodbook/security/jwt/JwtTokenFilter.java
Labels: ✨ Feature

#65 fix - 노출된 S3 키 삭제
  src/main/resources/application-local.yml
Labels: 🚮 chore

#73 [Feature] 기능 개발 - Moodbook 도서 서비스
  build.gradle
  src/main/java/org/com/moodbook/batch/config/BatchConfig.java
  src/main/java/org/com/moodbook/batch/dto/BatchBookResponse.java
  src/main/java/org/com/moodbook/batch/job/BookApiReader.java
  src/main/java/org/com/moodbook/batch/job/BookItemProcessor.java
  src/main/java/org/com/moodbook/batch/job/BookItemWriter.java
  src/main/java/org/com/moodbook/batch/scheduler/BookBatchScheduler.java
  src/main/java/org/com/moodbook/book/controller/BookController.java
  src/main/java/org/com/moodbook/book/dto/BookResponse.java
  src/main/java/org/com/moodbook/book/entity/Book.java
  src/main/java/org/com/moodbook/book/entity/BookCount.java
  src/main/java/org/com/moodbook/book/repository/BookCountRepository.java
  src/main/java/org/com/moodbook/book/repository/BookRepository.java
  src/main/java/org/com/moodbook/book/service/BookService.java
  src/main/java/org/com/moodbook/book/service/impl/BookServiceImpl.java
  src/main/java/org/com/moodbook/book/serviceImpl/BookServiceImpl.java
  src/main/java/org/com/moodbook/common/config/AladinApiProperties.java
  src/main/java/org/com/moodbook/common/config/QueryDslConfig.java
  src/main/java/org/com/moodbook/common/constants/CommonConstant.java
  src/main/java/org/com/moodbook/common/exception/BaseException.java
  src/main/resources/application-local.yml
Labels: ✨ Feature

#78 Feature/#59 - bookchat 기능구현
  src/main/java/org/com/moodbook/bookchat/controller/ChatRoomController.java
  src/main/java/org/com/moodbook/bookchat/dto/ApproveJoinRequest.java
  src/main/java/org/com/moodbook/bookchat/dto/ChatRoomMemberResponse.java
  src/main/java/org/com/moodbook/bookchat/dto/ChatRoomResponse.java
  src/main/java/org/com/moodbook/bookchat/dto/ChatRoomSearchRequest.java
  src/main/java/org/com/moodbook/bookchat/dto/CreateChatRoomRequest.java
  src/main/java/org/com/moodbook/bookchat/dto/MemberDTO.java
  src/main/java/org/com/moodbook/bookchat/dto/UpdateChatRoomRequest.java
  src/main/java/org/com/moodbook/bookchat/entity/ChatRoom.java
  src/main/java/org/com/moodbook/bookchat/entity/ChatRoomMember.java
  src/main/java/org/com/moodbook/bookchat/entity/ChatRoomMemberRole.java
  src/main/java/org/com/moodbook/bookchat/entity/ChatRoomMemberStatus.java
  src/main/java/org/com/moodbook/bookchat/entity/ChatRoomStatus.java
  src/main/java/org/com/moodbook/bookchat/repository/ChatRoomMemberRepository.java
  src/main/java/org/com/moodbook/bookchat/repository/ChatRoomRepository.java
  src/main/java/org/com/moodbook/bookchat/service/ChatRoomService.java
  src/main/java/org/com/moodbook/bookchat/service/ChatRoomServiceImpl.java
  src/main/java/org/com/moodbook/common/exception/ErrorCode.java
  src/main/java/org/com/moodbook/member/controller/MemberController.java
  src/main/java/org/com/moodbook/security/config/SecurityConfig.java
Labels: ✨ Feature

#91 Feature/#85 - BookEmotionRecommend; 메인페이지
  src/main/java/org/com/moodbook/book/controller/BookController.java
  src/main/java/org/com/moodbook/book/dto/BookEmotionRecommendAllRequest.java
  src/main/java/org/com/moodbook/book/dto/BookEmotionRecommendAllResponse.java
  src/main/java/org/com/moodbook/book/dto/BookEmotionRecommendRequest.java
  src/main/java/org/com/moodbook/book/dto/BookEmotionRecommendResponse.java
  src/main/java/org/com/moodbook/book/repository/BookRepository.java
  src/main/java/org/com/moodbook/book/service/BookService.java
  src/main/java/org/com/moodbook/book/service/impl/BookServiceImpl.java
  src/main/java/org/com/moodbook/emotion/repository/BookEmotionScoreRepository.java
  src/main/java/org/com/moodbook/emotion/repository/BookEmotionScoreRepositoryCustom.java
  src/main/java/org/com/moodbook/emotion/service/BookEmotionScoreRepositoryImpl.java
  src/main/java/org/com/moodbook/emotion/service/BookEmotionService.java
Labels: ✨ Feature

#93 [Bug] 버그 수정 - Jwt Token 인증 로그인 방식 에러 수정
  src/main/java/org/com/moodbook/member/service/MemberServiceImpl.java
  src/main/java/org/com/moodbook/security/authentication/service/AuthenticationServiceImpl.java
  src/main/java/org/com/moodbook/security/config/SecurityConfig.java
  src/main/java/org/com/moodbook/security/jwt/JwtProperties.java
  src/main/java/org/com/moodbook/security/jwt/JwtTokenFilter.java
  src/main/java/org/com/moodbook/security/jwt/JwtTokenProvider.java
Labels: 🐞 Bugfix

#95 [Feature] 기능 개발 - 도서, 리뷰, 최신 이력 조회 서비스 + Swagger 추가
  build.gradle
  src/main/java/org/com/moodbook/book/controller/BookController.java
  src/main/java/org/com/moodbook/book/service/BookService.java
  src/main/java/org/com/moodbook/book/service/impl/BookServiceImpl.java
  src/main/java/org/com/moodbook/common/config/SwaggerConfig.java
  src/main/java/org/com/moodbook/recentbookviews/controller/RecentBookViewController.java
  src/main/java/org/com/moodbook/recentbookviews/dto/ApiResponse.java
  src/main/java/org/com/moodbook/recentbookviews/dto/RecentBookViewResponse.java
  src/main/java/org/com/moodbook/recentbookviews/entity/RecentBookView.java
  src/main/java/org/com/moodbook/recentbookviews/repository/RecentBookViewRepository.java
  src/main/java/org/com/moodbook/recentbookviews/service/RecentBookViewService.java
  src/main/java/org/com/moodbook/recentbookviews/service/impl/RecentBookViewServiceImpl.java
  src/main/java/org/com/moodbook/review/controller/ReviewController.java
  src/main/java/org/com/moodbook/review/dto/ReviewRequest.java
  src/main/java/org/com/moodbook/review/dto/ReviewResponse.java
  src/main/java/org/com/moodbook/review/dto/ReviewUpdateRequest.java
  src/main/java/org/com/moodbook/review/entity/Review.java
  src/main/java/org/com/moodbook/review/repository/ReviewRepository.java
  src/main/java/org/com/moodbook/review/service/ReviewService.java
  src/main/java/org/com/moodbook/review/service/impl/ReviewServiceImpl.java
  src/main/java/org/com/moodbook/security/config/SecurityConfig.java
  src/main/resources/application.yml
  src/test/java/org/com/moodbook/review/repository/ReviewRepositoryTest.java
  src/test/java/org/com/moodbook/review/service/impl/ReviewServiceImplTest.java
Labels: ✨ Feature, ✅ Test

#98 [Hotfix] Review 관련 예외 처리 기능 처리 #97
  src/main/java/org/com/moodbook/common/exception/BaseException.java
  src/main/java/org/com/moodbook/common/exception/ErrorCode.java
Labels: 🐞 Bugfix

#105 Feat/#90 - 북마크 관련 기능을 위한 Controller, Service 추가
  src/main/java/org/com/moodbook/bookmark/controller/BookmarkController.java
  src/main/java/org/com/moodbook/bookmark/dto/BookmarkRequestDTO.java
  src/main/java/org/com/moodbook/bookmark/dto/BookmarkResponseDTO.java
  src/main/java/org/com/moodbook/bookmark/entity/Bookmark.java
  src/main/java/org/com/moodbook/bookmark/repository/BookmarkRepository.java
  src/main/java/org/com/moodbook/bookmark/service/BookmarkService.java
  src/main/java/org/com/moodbook/bookmark/service/BookmarkServiceImpl.java
  src/main/java/org/com/moodbook/common/exception/BaseException.java
  src/main/java/org/com/moodbook/common/exception/ErrorCode.java
Labels: ✨ Feature

#107 [BugFix] 엔티티 및 의존성 수정
  build.gradle
  src/main/java/org/com/moodbook/post/entity/Meeting.java
  src/main/java/org/com/moodbook/post/entity/Report.java
Labels: ✨ Feature, 🐞 Bugfix

#115 Feature/#111 - 감정 별 책 추천 조회 로직변경
  src/main/java/org/com/moodbook/book/controller/BookController.java
  src/main/java/org/com/moodbook/book/dto/BookEmotionAnalyzeResponse.java
  src/main/java/org/com/moodbook/book/dto/BookEmotionRecommendAllRequest.java
  src/main/java/org/com/moodbook/book/service/BookService.java
  src/main/java/org/com/moodbook/book/service/impl/BookServiceImpl.java
  src/main/java/org/com/moodbook/emotion/controller/EmotionAnalyzeViewController.java
  src/main/java/org/com/moodbook/security/config/SecurityConfig.java
  src/main/resources/templates/emotion-analyze.html
  src/main/resources/templates/login.html
Labels: ✨ Feature, 🔧 Refactor

#116 [Feature] 기능 개발 - SSE 활용한 채팅방 관련 실시간 알림 서비스 #114
  src/main/java/org/com/moodbook/bookchat/controller/ChatRoomController.java
  src/main/java/org/com/moodbook/bookchat/dto/ApproveJoinRequest.java
  src/main/java/org/com/moodbook/bookchat/entity/ChatRoomMember.java
  src/main/java/org/com/moodbook/bookchat/repository/ChatRoomMemberRepository.java
  src/main/java/org/com/moodbook/bookchat/service/ChatRoomService.java
  src/main/java/org/com/moodbook/bookchat/service/ChatRoomServiceImpl.java
  src/main/java/org/com/moodbook/common/constants/NotifyType.java
  src/main/java/org/com/moodbook/common/exception/BaseException.java
  src/main/java/org/com/moodbook/common/exception/ErrorCode.java
  src/main/java/org/com/moodbook/notification/controller/NotificationController.java
  src/main/java/org/com/moodbook/notification/dto/NotificationResponse.java
  src/main/java/org/com/moodbook/notification/dto/UpdateNotificationRequest.java
  src/main/java/org/com/moodbook/notification/dto/UpdateNotificationResponse.java
  src/main/java/org/com/moodbook/notification/entity/Notifications.java
  src/main/java/org/com/moodbook/notification/repository/EmitterRepository.java
  src/main/java/org/com/moodbook/notification/repository/NotificationRepository.java
  src/main/java/org/com/moodbook/notification/service/NotificationService.java
  src/main/java/org/com/moodbook/security/config/SecurityConfig.java
Labels: ✨ Feature

#113 feat/#109 - 사용자의 현재 감정 선택 기능 개발
  src/main/java/org/com/moodbook/bookmark/service/BookmarkServiceImpl.java
  src/main/java/org/com/moodbook/common/util/EmotionInitializer.java
  src/main/java/org/com/moodbook/emotion/controller/MemberEmotionController.java
  src/main/java/org/com/moodbook/emotion/dto/MemberEmotionDTO.java
  src/main/java/org/com/moodbook/emotion/entity/Emotion.java
  src/main/java/org/com/moodbook/emotion/entity/MemberEmotion.java
  src/main/java/org/com/moodbook/emotion/entity/MemberEmotionId.java
  src/main/java/org/com/moodbook/emotion/repository/EmotionRepository.java
  src/main/java/org/com/moodbook/emotion/repository/MemberEmotionRepository.java
  src/main/java/org/com/moodbook/emotion/service/MemberEmotionService.java
  src/main/java/org/com/moodbook/emotion/service/MemberEmotionServiceImpl.java
Labels: ✨ Feature

#117 Feat/#112 독서모임글과 채팅방의 연결을 위한 코드 수정
  src/main/java/org/com/moodbook/bookchat/repository/ChatRoomMemberRepository.java
  src/main/java/org/com/moodbook/post/controller/MeetingController.java
  src/main/java/org/com/moodbook/post/dto/ChatLinkRequest.java
  src/main/java/org/com/moodbook/post/dto/CreateMeetingRequest.java
  src/main/java/org/com/moodbook/post/dto/MeetingDetailResponse.java
  src/main/java/org/com/moodbook/post/dto/MeetingSummaryResponse.java
  src/main/java/org/com/moodbook/post/entity/Meeting.java
  src/main/java/org/com/moodbook/post/entity/MeetingMember.java
  src/main/java/org/com/moodbook/post/repository/MeetingMemberRepository.java
  src/main/java/org/com/moodbook/post/service/MeetingService.java
  src/main/java/org/com/moodbook/post/service/impl/MeetingServiceImpl.java
Labels: ✨ Feature, 🔧 Refactor

#121 Feature/#84 redis
  src/main/java/org/com/moodbook/common/config/RedisConfig.java
  src/main/java/org/com/moodbook/common/exception/BaseException.java
  src/main/java/org/com/moodbook/common/exception/ErrorCode.java
  src/main/java/org/com/moodbook/common/util/EmailUtil.java
  src/main/java/org/com/moodbook/member/service/MemberServiceImpl.java
  src/main/java/org/com/moodbook/security/authentication/controller/EmailAuthenticationController.java
  src/main/java/org/com/moodbook/security/authentication/controller/RedisTestController.java
  src/main/java/org/com/moodbook/security/authentication/entity/Authentication.java
  src/main/java/org/com/moodbook/security/authentication/service/EmailAuthenticationService.java
  src/main/java/org/com/moodbook/security/authentication/service/EmailAuthenticationServiceImpl.java
  src/main/java/org/com/moodbook/security/config/SecurityConfig.java
Labels: ✨ Feature

#123 [Chore] 도서 서비스 전체 조회 기능 추가 + Swagger 문서 작성
  src/main/java/org/com/moodbook/awss3/controller/AWSS3Controller.java
  src/main/java/org/com/moodbook/book/controller/BookController.java
  src/main/java/org/com/moodbook/book/repository/BookRepository.java
  src/main/java/org/com/moodbook/book/service/BookService.java
  src/main/java/org/com/moodbook/book/service/impl/BookServiceImpl.java
  src/main/java/org/com/moodbook/bookchat/controller/ChatRoomController.java
  src/main/java/org/com/moodbook/bookmark/controller/BookmarkController.java
  src/main/java/org/com/moodbook/emotion/controller/EmotionController.java
  src/main/java/org/com/moodbook/emotion/controller/MemberEmotionController.java
  src/main/java/org/com/moodbook/member/controller/MemberController.java
  src/main/java/org/com/moodbook/notification/controller/NotificationController.java
  src/main/java/org/com/moodbook/post/controller/CommentController.java
  src/main/java/org/com/moodbook/post/controller/LikeController.java
  src/main/java/org/com/moodbook/post/controller/MeetingController.java
  src/main/java/org/com/moodbook/post/controller/ReportController.java
  src/main/java/org/com/moodbook/post/controller/TagController.java
  src/main/java/org/com/moodbook/review/controller/ReviewController.java
Labels: 🚮 chore

#126 Feat/#125 엘라스틱서치 관련 설정 제거
  build.gradle
  docker-compose.yml
  src/main/java/org/com/moodbook/MoodbookApplication.java
Labels: ⚙️ Setting, 🐞 Bugfix

#128 Feature/#87 관리자 책 관리 페이지 추가 및 기존 기능 수정
  src/main/java/org/com/moodbook/admin/AdminMainController.java
  src/main/java/org/com/moodbook/admin/book/controller/AdminBookController.java
  src/main/java/org/com/moodbook/admin/book/dto/AdminBookDTO.java
  src/main/java/org/com/moodbook/admin/book/repository/AdminBookRepository.java
  src/main/java/org/com/moodbook/admin/book/service/AdminBookService.java
  src/main/java/org/com/moodbook/admin/book/service/impl/AdminBookServiceImpl.java
  src/main/java/org/com/moodbook/admin/chat/service/impl/AdminChatRoomServiceImpl.java
  src/main/java/org/com/moodbook/admin/member/controller/AdminMemberController.java
  src/main/java/org/com/moodbook/admin/member/service/AdminMemberService.java
  src/main/java/org/com/moodbook/admin/member/service/impl/AdminMemberServiceImpl.java
  src/main/java/org/com/moodbook/batch/job/BookApiReader.java
  src/main/java/org/com/moodbook/book/entity/Book.java
  src/main/java/org/com/moodbook/book/entity/BookCount.java
  src/main/java/org/com/moodbook/security/config/SecurityConfig.java
  src/main/resources/templates/admin/book.html
  src/main/resources/templates/admin/book_add.html
  src/main/resources/templates/admin/main.html
  src/main/resources/templates/chatroom/chat-rooms.html
Labels: ✨ Feature

#129 Feat/#127 게시글 소프트딜리트 쿼리문 수정 및 ES import문 제거
  src/main/java/org/com/moodbook/MoodbookApplication.java
  src/main/java/org/com/moodbook/post/entity/BasePost.java
Labels: 🔧 Refactor

#149 [CI/CD] 배포 작업 - Jenkins Backend 프로젝트 Cloud 테스트 #143
  Dockerfile
  docker-compose.backend.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🤖 CI/CD

#150 feat/#142 : 알라딘 api 호출
  src/main/java/org/com/moodbook/book/controller/AladinBookController.java
  src/main/java/org/com/moodbook/book/dto/AladinBookResponse.java
  src/main/java/org/com/moodbook/book/repository/BookRepository.java
  src/main/java/org/com/moodbook/book/service/AladinApiService.java
  src/main/java/org/com/moodbook/book/service/BookService.java
  src/main/java/org/com/moodbook/book/service/impl/AladinApiServiceImpl.java
  src/main/java/org/com/moodbook/book/service/impl/BookServiceImpl.java
Labels: ✨ Feature

#162 feat(service)- 인증 bug fix
  src/main/java/org/com/moodbook/security/authentication/service/AuthenticationServiceImpl.java
Labels: 🐞 Bugfix

#145 Feat/#139 - Swagger 페이지 반환타입 확인을 위한 Controller Return Type 수정
  src/main/java/org/com/moodbook/awss3/controller/AWSS3Controller.java
  src/main/java/org/com/moodbook/bookmark/controller/BookmarkController.java
  src/main/java/org/com/moodbook/mypage/controller/MyPageController.java
Labels: 🚮 chore

#165 배포 작업 - ELK + Prometheus + Grafana 작업 시작 #163
  .gitignore
  build.gradle
  src/main/java/org/com/moodbook/security/config/SecurityConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/logback-spring.xml
Labels: 🤖 CI/CD

#167 cicd: application.yml (prod 로 수정) (#166)
  src/main/resources/application.yml
Labels: 🐞 Bugfix

#180 setting: log 모니터링 위한 prod 환경 활성화 (#179)
  src/main/resources/logback-spring.xml
Labels: ⚙️ Setting

#185 chore: logback-spring.xml 수정 (#183)
  src/main/resources/logback-spring.xml
Labels: 🚮 chore

#186 Feature/#160 - bookList es 기능 개발(자동완성, 검색기능)
  src/main/java/org/com/moodbook/book/controller/BookController.java
  src/main/java/org/com/moodbook/book/elasticsearch/controller/BookEsController.java
  src/main/java/org/com/moodbook/book/elasticsearch/controller/BookViewController.java
  src/main/java/org/com/moodbook/book/elasticsearch/dto/BookEsDocument.java
  src/main/java/org/com/moodbook/book/elasticsearch/repository/BookEsRepository.java
  src/main/java/org/com/moodbook/book/elasticsearch/service/BookEsService.java
  src/main/java/org/com/moodbook/book/entity/BookCount.java
  src/main/java/org/com/moodbook/emotion/controller/EmotionController.java
  src/main/java/org/com/moodbook/security/authentication/service/AuthenticationServiceImpl.java
  src/main/java/org/com/moodbook/security/config/SecurityConfig.java
  src/main/resources/templates/book/list.html
Labels: ✨ Feature

#196 Feat/#144 독후감 독서모임에 대한 엘라스틱 서치 검색기능 개발
  build.gradle
  src/main/java/org/com/moodbook/post/repository/MeetingRepository.java
  src/main/java/org/com/moodbook/post/repository/ReportRepository.java
  src/main/java/org/com/moodbook/post/search/controller/MeetingEsController.java
  src/main/java/org/com/moodbook/post/search/controller/ReportEsController.java
  src/main/java/org/com/moodbook/post/search/document/MeetingEsDocument.java
  src/main/java/org/com/moodbook/post/search/document/ReportEsDocument.java
  src/main/java/org/com/moodbook/post/search/repository/MeetingEsRepository.java
  src/main/java/org/com/moodbook/post/search/repository/ReportEsRepository.java
  src/main/java/org/com/moodbook/post/search/service/MeetingEsService.java
  src/main/java/org/com/moodbook/post/search/service/ReportEsService.java
  src/main/resources/elasticsearch/meeting-mappings.json
  src/main/resources/elasticsearch/meeting-settings.json
  src/main/resources/elasticsearch/report-mappings.json
  src/main/resources/elasticsearch/report-settings.json
Labels: ✨ Feature

#198 bugfix: build.gradle 수정 (#197)
  build.gradle
Labels: 🐞 Bugfix

#202 Feat/#178 - 독서모임 관련 기능 수정
  src/main/java/org/com/moodbook/bookchat/controller/ChatRoomController.java
  src/main/java/org/com/moodbook/bookchat/dto/UpdateChatRoomRequest.java
  src/main/java/org/com/moodbook/bookchat/service/ChatRoomServiceImpl.java
Labels: ✨ Feature

#204 Feature/#201 - 책 ES 검색 인덱스 파일 동기화
  src/main/java/org/com/moodbook/batch/job/BookItemWriter.java
  src/main/java/org/com/moodbook/book/eventlistener/event/BookCreatedEvent.java
  src/main/java/org/com/moodbook/book/eventlistener/listener/BookEsSyncListener.java
  src/main/java/org/com/moodbook/book/service/BookService.java
  src/main/java/org/com/moodbook/book/service/impl/BookServiceImpl.java
  src/main/java/org/com/moodbook/bookchat/dto/ApproveJoinRequest.java
  src/main/java/org/com/moodbook/emotion/controller/EmotionController.java
  src/main/java/org/com/moodbook/emotion/repository/BookEmotionScoreRepository.java
  src/main/java/org/com/moodbook/emotion/service/BookEmotionScoreRepositoryImpl.java
Labels: ✨ Feature

#206 기타 업무 - 채팅방 알림 기능 테스트 + JVM 메모리 최적화 + 로그 저장 기간 조정 #200
  docker-compose.backend.yml
  src/main/java/org/com/moodbook/bookchat/service/ChatRoomServiceImpl.java
  src/main/resources/logback-spring.xml
Labels: 🚮 chore

#209 bugfix: ChatRoomService 수정 (#208)
  src/main/java/org/com/moodbook/bookchat/service/ChatRoomServiceImpl.java
Labels: 🐞 Bugfix

#213 Feature/#154 member crud
  build.gradle
  src/main/java/org/com/moodbook/common/exception/BaseException.java
  src/main/java/org/com/moodbook/common/exception/ErrorCode.java
  src/main/java/org/com/moodbook/member/controller/MemberController.java
  src/main/java/org/com/moodbook/member/dto/LoginResponseDTO.java
  src/main/java/org/com/moodbook/member/dto/MemberLoginDTO.java
  src/main/java/org/com/moodbook/member/dto/MemberTempJoinDTO.java
  src/main/java/org/com/moodbook/member/entity/Member.java
  src/main/java/org/com/moodbook/member/service/MemberService.java
  src/main/java/org/com/moodbook/member/service/MemberServiceImpl.java
  src/main/java/org/com/moodbook/oauth2/OAuth2LoginSuccessHandler.java
  src/main/java/org/com/moodbook/security/authentication/controller/AuthenticationController.java
  src/main/java/org/com/moodbook/security/authentication/service/AuthenticationServiceImpl.java
  src/main/java/org/com/moodbook/security/authentication/service/EmailAuthenticationService.java
  src/main/java/org/com/moodbook/security/authentication/service/EmailAuthenticationServiceImpl.java
  src/main/java/org/com/moodbook/security/core/CustomMemberDetails.java
  src/main/java/org/com/moodbook/security/jwt/JwtTokenFilter.java
Labels: ✨ Feature

#218 Feat/#203 댓글, 좋아요, 독서모임 검색기능 리팩토링 및 구조개선
  build.gradle
  src/main/java/org/com/moodbook/post/controller/CommentController.java
  src/main/java/org/com/moodbook/post/controller/LikeController.java
  src/main/java/org/com/moodbook/post/controller/ReportController.java
  src/main/java/org/com/moodbook/post/dto/CommentResponse.java
  src/main/java/org/com/moodbook/post/dto/MeetingDetailResponse.java
  src/main/java/org/com/moodbook/post/dto/MeetingJoinDto.java
  src/main/java/org/com/moodbook/post/dto/MeetingJoinRequest.java
  src/main/java/org/com/moodbook/post/dto/MeetingJoinResponseRequest.java
  src/main/java/org/com/moodbook/post/dto/ReportDetailResponse.java
  src/main/java/org/com/moodbook/post/repository/CommentRepository.java
  src/main/java/org/com/moodbook/post/search/config/ElasticsearchConfig.java
  src/main/java/org/com/moodbook/post/search/document/MeetingEsDocument.java
  src/main/java/org/com/moodbook/post/service/CommentService.java
  src/main/java/org/com/moodbook/post/service/MeetingService.java
  src/main/java/org/com/moodbook/post/service/impl/CommentServiceImpl.java
  src/main/java/org/com/moodbook/post/service/impl/LikeServiceImpl.java
  src/main/java/org/com/moodbook/post/service/impl/ReportServiceImpl.java
Labels: ✨ Feature, 🐞 Bugfix

#219 성능 개선 - local, prod 분기 처리 #215
  build.gradle
  src/main/java/org/com/moodbook/MoodbookApplication.java
  src/main/java/org/com/moodbook/common/config/AppUrlProperties.java
  src/main/java/org/com/moodbook/security/authentication/controller/AuthenticationController.java
  src/main/java/org/com/moodbook/security/authentication/service/EmailAuthenticationServiceImpl.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 🎤 Perform

#223 hotfix: .env file 내용 제거 (#222)
  docker-compose.backend.yml
Labels: 🐞 Bugfix

#227 hotfix: .env에서 elasticsearch 적용 안 되는 부분 수정 (#226)
  src/main/resources/application-prod.yml
Labels: 🐞 Bugfix

#229 hotfix: .env에서 elasticsearch 적용 안 되는 부분 수정 (#228)
  src/main/resources/application-prod.yml
Labels: 🐞 Bugfix

#231 hotfix: .env에서 elasticsearch 버전 명시 + appllication-prod.yml 들여쓰기 수정
  build.gradle
  src/main/resources/application-prod.yml
Labels: 🐞 Bugfix

#240 bugfix: prod 적용 (#239)
  src/main/resources/application-prod.yml
Labels: 🐞 Bugfix

#245 bugfix: application.yml 수정 (#244)
  src/main/resources/application.yml
Labels: 🐞 Bugfix

#247 bugfix: mail 관련 내용 추가 (#246)
  docker-compose.backend.yml
Labels: 🐞 Bugfix

#249 bugfix: 메일 인증 관련 에러 처리 (#248)
  src/main/java/org/com/moodbook/common/config/AppUrlProperties.java
Labels: 🐞 Bugfix

#255 [Chore] 기타 작업 - 로그인한 사용자에 한해서만 등록되도록 수정[도서 서비스]
  src/main/java/org/com/moodbook/book/controller/BookController.java
  src/main/java/org/com/moodbook/book/service/BookService.java
  src/main/java/org/com/moodbook/book/service/impl/BookServiceImpl.java
Labels: 🚮 chore

#261 Feature/#256 - 채팅데이터 redis, mongodb에 저장
  build.gradle
  src/main/java/org/com/moodbook/security/config/SecurityConfig.java
  src/main/java/org/com/moodbook/security/jwt/JwtTokenFilter.java
  src/main/java/org/com/moodbook/threadlocal/TraceIdHolder.java
  src/main/java/org/com/moodbook/websocket/chatmessage/chatflush/config/ChatFlushConfig.java
  src/main/java/org/com/moodbook/websocket/chatmessage/chatflush/manager/ChatFlushManager.java
  src/main/java/org/com/moodbook/websocket/chatmessage/chatflush/strategy/ChatFlushStrategy.java
  src/main/java/org/com/moodbook/websocket/chatmessage/chatflush/strategy/CountBasedFlushStrategy.java
  src/main/java/org/com/moodbook/websocket/chatmessage/chatflush/strategy/TimeBasedFlushStrategy.java
  src/main/java/org/com/moodbook/websocket/chatmessage/controller/ChatMessageController.java
  src/main/java/org/com/moodbook/websocket/chatmessage/dto/ChatMessageDocumentResponse.java
  src/main/java/org/com/moodbook/websocket/chatmessage/entity/ChatMessageDocument.java
  src/main/java/org/com/moodbook/websocket/chatmessage/redis/ChatMessageCache.java
  src/main/java/org/com/moodbook/websocket/chatmessage/redis/ChatMessageRedisRepository.java
  src/main/java/org/com/moodbook/websocket/chatmessage/repository/ChatMessageMongoRepository.java
  src/main/java/org/com/moodbook/websocket/chatmessage/service/ChatMessageService.java
  src/main/java/org/com/moodbook/websocket/config/JacksonConfig.java
  src/main/java/org/com/moodbook/websocket/controller/ChatController.java
Labels: ✨ Feature

#263 Refactor/#262 - 소셜 로그인 리다이렉트 URL + Swagger 수정
  src/main/java/org/com/moodbook/oauth2/OAuth2LoginSuccessHandler.java
  src/main/java/org/com/moodbook/websocket/chatmessage/controller/ChatMessageController.java
Labels: 🔧 Refactor

#260 Feat/#258 - 북마크 추가 관련 기능 수정, Book관련 코드 수정
  src/main/java/org/com/moodbook/book/controller/BookController.java
  src/main/java/org/com/moodbook/book/dto/BookEmotionRecommendAllRequest.java
  src/main/java/org/com/moodbook/book/dto/BookEmotionRecommendRequest.java
  src/main/java/org/com/moodbook/book/service/BookService.java
  src/main/java/org/com/moodbook/book/service/impl/BookServiceImpl.java
  src/main/java/org/com/moodbook/bookmark/controller/BookmarkController.java
Labels: ✨ Feature

#274 Fix/#273
  src/main/java/org/com/moodbook/member/controller/MemberController.java
  src/main/java/org/com/moodbook/member/service/MemberService.java
  src/main/java/org/com/moodbook/member/service/MemberServiceImpl.java
  src/main/java/org/com/moodbook/security/authentication/controller/AuthenticationController.java
  src/main/java/org/com/moodbook/security/authentication/dto/PasswordResetRequestDto.java
  src/main/java/org/com/moodbook/security/authentication/service/EmailAuthenticationServiceImpl.java
  src/main/java/org/com/moodbook/security/config/SecurityConfig.java
  src/main/java/org/com/moodbook/security/jwt/JwtTokenFilter.java
Labels: 🐞 Bugfix

#277 Cicd/#275 - 카카오 소셜 로그인
  docker-compose.backend.yml
  src/main/resources/application-prod.yml
Labels: 🤖 CI/CD

#282 Feature/#281 경로수정
  src/main/java/org/com/moodbook/member/controller/MemberController.java
  src/main/java/org/com/moodbook/security/config/SecurityConfig.java
Labels: ✨ Feature, 🔧 Refactor

#287 bugfix: 프론트에서 이미지 깨지는 이슈 처리 (#286)
  src/main/resources/static/admin/images/gendo.png
  src/main/resources/static/admin/images/logo.png
  src/main/resources/static/admin/images/onion.png
  src/main/resources/static/admin/sounds/bounce.mp3
  src/main/resources/templates/admin/book.html
  src/main/resources/templates/admin/book_add.html
  src/main/resources/templates/admin/chat.html
  src/main/resources/templates/admin/main.html
  src/main/resources/templates/admin/member.html
Labels: 🐞 Bugfix

#293 chore: 페이징 처리 + 알라딘 API 호출 횟수 증가 처리 + 관리자 페이지 mp3 부분 처리 (#290)
  src/main/java/org/com/moodbook/batch/scheduler/BookBatchScheduler.java
  src/main/java/org/com/moodbook/book/controller/BookController.java
  src/main/java/org/com/moodbook/common/constants/CommonConstant.java
  src/main/java/org/com/moodbook/recentbookviews/controller/RecentBookViewController.java
  src/main/resources/templates/admin/main.html
Labels: 🐞 Bugfix

#297 feat/#296 : 엘라스틱서치 인덱스 변경
  src/main/java/org/com/moodbook/book/elasticsearch/dto/BookEsAutoCompleteDocument.java
  src/main/java/org/com/moodbook/book/elasticsearch/repository/BookEsAutoCompleteRepository.java
  src/main/java/org/com/moodbook/book/elasticsearch/service/BookEsService.java
Labels: ✨ Feature
